# Generated by Django 4.0.5 on 2022-06-14 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('music_link', models.CharField(max_length=200)),
                ('website_link', models.CharField(max_length=200)),
                ('photo_link', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Instrument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SkillLevel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('bio', models.CharField(max_length=200)),
                ('email', models.CharField(max_length=50)),
                ('resume_link', models.CharField(max_length=200)),
                ('audition_video_link', models.CharField(max_length=200)),
                ('photo_link', models.CharField(max_length=200)),
                ('instruments', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.instrument')),
                ('musician', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('skill_level', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.skilllevel')),
            ],
        ),
        migrations.CreateModel(
            name='Gig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gig_name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('date', models.DateTimeField()),
                ('description', models.CharField(max_length=300)),
                ('venue', models.CharField(max_length=100)),
                ('photo_link', models.CharField(max_length=200)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.artist')),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.genre')),
                ('gigs_submitted_to', models.ManyToManyField(related_name='gigs', to='app_api.musician')),
                ('instruments_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.instrument')),
                ('skill_level_needed', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.skilllevel')),
            ],
        ),
        migrations.AddField(
            model_name='artist',
            name='genre',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app_api.genre'),
        ),
        migrations.AddField(
            model_name='artist',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
